### ISSUE TITLE
Incompatibility issue with Puppet 5

### ISSUE THREAD

**Issue by craigcarnell** [mattpatterson/puppet-clam#5]
I'm in the process of converting my own modules to version 5 syntax, there is currently an error in clam module:

```
Filepath: /etc/puppetlabs/code/environments/production/modules/clam/templates/clam.sh.erb
  Line: 7
  Detail: undefined local variable or method `scan_directory' for #<Puppet::Parser::TemplateWrapper:0x3df92d85>
```

The scan_directory needs @ in front of it in the template like so:

```
<%= @scan_directory -%>
```

**Comment by craigcarnell** [comment]
https://github.com/mattpatterson/puppet-clam/pull/6

**Comment by mattpatterson** [comment]
Merged in your requests...Thanks!
